language: java
jdk:
  - openjdk11

# main 브랜치에 push될 때만 수행한다.
branches:
  only:
    - main

# 의존성을 캐시하는 부분. 다음 배포 때부터는 캐시된 결과를 사용하도록 한다.
cache:
  directories:
    - '$HOME/.gradle'

# main 브랜치에 푸시되었을 때 수행되는 명령어다.
script: "./gradlew clean build"

# CI 실행 완료 후 메일로 알람
notifications:
  email:
    recipients:
      - layer6ai@gmail.com
